# .config/wireplumber/wireplumber.conf.d/98-fix-audio-devices.conf
#
# Author: Masq
# Date: 2025-09-23
# Description: Renames certain devices and disables useless ones in Pipewire via Wireplumber
#

monitor.alsa.rules = [{

	# Rename/Update our Headset Speakers
	matches = [{
		# wpctl status -n
		# This is the back of the machine's Line Out hardware jack/port
		node.name = "alsa_output.usb-Generic_USB_Audio-00.HiFi__Speaker__sink"
	}],

	actions = {
		# We want to update the device to appear as headphones and be called "Headset"
		update-props = {
			node.description = "Headset Speakers (Back Panel)",
			node.nick = "Headset Speakers (Back Panel)",
			device.form-factor = "headset",
			# What is the difference between symbolic and not for audio-headset?
			# device.icon_name = "audio-headset",
			device.icon_name = "audio-headset-symbolic",

			device.profile-set = "simple-headphones-mic",
			#device.profile-set = "usb-gaming-headset",
			#device.profile = "usb-gaming-headset"
		}
	}
}, {

	# Rename/Update our Headset Mic
	matches = [{
		# wpctl status -n
		# This is the back of the machine's Line Out hardware jack/port
		node.name = "alsa_input.usb-Generic_USB_Audio-00.HiFi__Mic1__source"
	}, {
		# wpctl status -n
		# This is the back of the machine's Line Out hardware jack/port
		node.name = "alsa_input.usb-Generic_USB_Audio-00.HiFi__Mic__source"
	}],

	actions = {
		# We want to update the device to appear as headphones and be called "Headset"
		update-props = {
			node.description = "Headset Mic (Back Panel)",
			node.nick = "Headset Mic (Back Panel)",
			device.form-factor = "headset",
			# What is the difference between symbolic and not for audio-headset?
			# device.icon_name = "audio-headset",
			device.icon_name = "audio-headset-symbolic",

			device.profile-set = "simple-headphones-mic",
			#device.profile-set = "usb-gaming-headset",
			#device.profile = "usb-gaming-headset"
		}
	}
}, {

	# Rename/Update our Computer's Audio from "USB Audio" (Not actually from a USB port...)
	# I think this is a result of the ALC4080 representing things as USB audio...
	matches = [{
		# wpctl status -n
		# This is the back of the machine's Line Out hardware jack/port
		node.name = "alsa_card.usb-Generic_USB_Audio-00"
	}],

	actions = {
		# Update name of the Device to be something more obvious/clear
		update-props = {
			node.description = "MoBo ALC4080 Audio",
			node.nick = "MoBo ALC4080 Audio",
		}
	}

}, {
	# Devices to disable. Helps remove clutter from audio controls
	matches = [{
		# Back panel "digital audio" port. I absolutely never use this.
		node.name = "alsa_output.usb-Generic_USB_Audio-00.HiFi__SPDIF__sink"
	}, {
		# Back panel Line In port. I will likely never use this.
		node.name = "alsa_input.usb-Generic_USB_Audio-00.HiFi__Line1__source"
	}, {
		# Back panel Line In port. I will likely never use this.
		node.name = "alsa_input.usb-Generic_USB_Audio-00.HiFi__Line__source"
	}, {
		# Front panel headset port... we might want to have this able to be used at some point...
		node.name = "alsa_output.usb-Generic_USB_Audio-00.HiFi__Headphones__sink"
	}, {
		# Frankly, I'm not sure what this is... I think it has to do with the GPU Audio via HDMI?
		node.name = "alsa_card.pci-0000_01_00.1"
	}, {
		# Frankly, I'm not sure what this is... maybe audio from the MoBo that doesn't have any
		# downstream sinks or sources???
		node.name = "alsa_card.pci-0000_11_00.1"
	}],

	# Set them to disabled
	actions = {
		update-props = {
			node.disabled = true
		}
	}
}]
