;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #BCC3C3
background-alt = #002B36
foreground = #002B36
foreground-alt = #BCC3C3
primary = #ffb52a
secondary = #e60053
alert = #FF0000

[bar/_base]
monitor = ${env:MONITOR:}
width = 100%
height = 22
radius = 0.0
fixed-center = true
top = no
bottom = yes
override-redirect = false

foreground = ${colors.foreground-alt}
background = ${colors.background-alt}

; Under-/overline pixel size and argb color
; Individual values can be defined using:
;   {overline,underline}-size
;   {overline,underline}-color
line-size = 1
line-color = #dfdfdf

border-top-size = 0
border-bottom-size = 0
border-left-size = 0
border-right-size = 0

padding-left = 0
padding-right = 0

module-margin-left = 0
module-margin-right = 0

font-0 = Hack:pixelsize=9;3
font-1 = Weather Icons:style=Regular:size=10;4
font-2 = "Wuncon Siji:pixelsize=10;3"
font-3 = FontAwesome5Free:style=Solid:pixelsize=10;3
font-4 = FontAwesome5Brands:style=Solid:pixelsize=10;3
font-5 = Noto Sans Symbols 2:style=Regular:size=10;4

wm-restack = i3

scroll-up = #i3.next
scroll-down = #i3.prev

cursor-click = pointer


[bar/primary]
inherit = bar/_base

; linux-ver
; info-hackspeed
modules-left = i3 spr media-player spm volume
modules-right = weather spm updates spm protonvpn spl date spl tray

[bar/secondary]
inherit = bar/_base

; linux-ver
; info-hackspeed
modules-left = i3 spr media-player spm volume
modules-right = weather spm protonvpn spl date

[module/spm]
type = custom/text
format = " | "
format-foreground = #93A1A1
format-background = ${colors.background-alt}

[module/spl]
type = custom/text
format = " |"
format-foreground = #93A1A1
format-background = ${colors.background-alt}

[module/spr]
type = custom/text
format = "| "
format-foreground = #93A1A1
format-background = ${colors.background-alt}


[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
strip-wsnumbers = true
enable-click = true
enable-scroll = false

; web icon potential: 🕸
ws-icon-0 = 1:mail;🖂
ws-icon-1 = 2:web;🌎
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9:media;🎜
ws-icon-9 = 10:sys;📊
ws-icon-default = ""

label-mode = %mode%
label-mode-padding = 1
label-mode-foreground = ${colors.foreground-alt}
label-mode-background = ${colors.background-alt}

; focused = Active workspace on focused monitor
label-focused = %index%:%name%
label-focused-foreground = ${colors.foreground}
label-focused-background = ${colors.background}
label-focused-underline = ${colors.foreground-alt}
label-focused-padding = 1

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%:%name%
label-unfocused-padding = ${self.label-focused-padding}
label-unfocused-foreground = ${colors.foreground-alt}
label-unfocused-background = ${colors.background-alt}

; visible = Active workspace on unfocused monitor
label-visible = %index%:%name%
label-visible-foreground = ${self.label-focused-background}
label-visible-background = ${self.label-focused-foreground}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%:%name%
label-urgent-foreground = ${colors.foreground}
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

; Separator in between workspaces
label-separator =
label-separator-padding = 0
label-separator-foreground = #fff

[module/tray]
type = internal/tray
format-margin = 4px
tray-spacing = 8px
tray-size = 14
tray-background = ${colors.background-alt}
tray-foreground = ${colors.foreground-alt}

[module/media-player]
type = custom/script
exec = ~/.config/polybar/scripts/media-player.sh
interval = 5

[module/weather]
type = custom/script
exec = ~/.config/polybar/scripts/weather-openmap.sh
interval = 600
label-font = 2
label = %{T2}%output%%{T-}

[module/linux-ver]
type = custom/script
exec = uname -r
interval = 600

[module/updates]
type = custom/script
exec = ~/.config/polybar/scripts/arch_updates.sh
; 60*seconds * 60*minutes * 6*hours = 21600*seconds
interval = 21600
label = %output%

[module/date]
type = internal/date
interval = 1

time = "%Y-%m-%d %H:%M:%S (%A)"

format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-prefix-background = ${colors.background-alt}

label = %time%
label-foreground = ${colors.foreground-alt}
label-background = ${colors.background-alt}

[module/protonvpn]
type = custom/script
exec = ~/.config/polybar/scripts/protonvpn.sh
interval = 5
label = %output%

[module/volume]
type = internal/pulseaudio
; Available tags:
;   <label-volume> (default)
;   <ramp-volume>
;   <bar-volume>
format-volume = <label-volume>

; Available tags:
;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
format-muted = <label-muted>

; Available tokens:
;   %percentage% (default)
;   %decibels%
label-volume = Volume:%percentage%%
label-muted = Volume:%percentage%% 
label-muted-foreground = #FF6

; Only applies if <ramp-volume> is used
ramp-volume-0 = 🔈
ramp-volume-1 = 🔉
ramp-volume-2 = 🔊

; Right and Middle click
click-right = pavucontrol
; click-middle = 


[module/alsa]
type = internal/alsa

; Soundcard to be used
; Usually in the format hw:# where # is the card number
; You can find the different card numbers in `/proc/asound/cards`
master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default

; Name of the master, speaker and headphone mixers
; Use the following command to list available mixer controls:
; $ amixer scontrols | sed -nr "s/.*'([[:alnum:]]+)'.*/\1/p"
; If master, speaker or headphone-soundcard isn't the default,
; use `amixer -c # scontrols` instead where # is the number
; of the master, speaker or headphone soundcard respectively
;
; Default: Master
master-mixer = Master

format-volume = "<label-volume><bar-volume>"
label-volume = " "
label-volume-foreground = ${colors.foreground-alt}
label-volume-background = ${colors.background-alt}

format-muted-prefix = " "
format-muted-foreground = ${colors.foreground-alt}
format-muted-background = ${colors.background-alt}
label-muted = MUTED

bar-volume-width = 5
bar-volume-foreground-0 = ${colors.foreground-alt}
bar-volume-foreground-1 = ${colors.foreground-alt}
bar-volume-foreground-2 = ${colors.foreground-alt}
bar-volume-foreground-3 = ${colors.foreground-alt}
bar-volume-foreground-4 = ${colors.foreground-alt}
bar-volume-foreground-5 = ${colors.foreground-alt}
bar-volume-foreground-6 = ${colors.foreground-alt}
bar-volume-gradient = false
bar-volume-indicator = []
bar-volume-indicator-font = 1
bar-volume-indicator-foreground = ${colors.foreground-alt}
bar-volume-indicator-background = ${colors.background-alt}
bar-volume-fill = -
bar-volume-fill-font = 1
bar-volume-fill-foreground = ${colors.foreground-alt}
bar-volume-fill-background = ${colors.background-alt}
bar-volume-empty = -
bar-volume-empty-font = 1
bar-volume-empty-foreground = ${colors.foreground-alt}
bar-volume-empty-background = ${colors.background-alt}

; [module/info-hackspeed]
; type = custom/script
; exec = ~/.config/polybar/scripts/info-hackspeed.sh
; tail = true

[settings]
throttle-output = 5
throttle-output-for = 10
;throttle-input-for = 30
screenchange-reload = true
compositing-background = over
compositing-foreground = over
compositing-overline = over
compositing-border = over

[global/wm]
margin-top = 5
margin-bottom = 5
